---
achievements:
  shortcuts:
    achievements: achievement
  types:
    community: fa-id-badge
    portal: fa-globe
    fs3: fa-bullseye
    story: fa-user-astronaut
    accommodations: fa-medal
    qualifications: fa-angle-double-up
    marks: fa-angle-double-down
    medical: fa-heartbeat
    compliments: fa-comments
