---
demographics:
  census_fields:
  - field: name
    width: 22
    title: Name
  - field: demographic
    width: 10
    title: Gender
    value: gender
  - field: group
    width: 26
    title: Rank
    value: Rank
  - field: group
    width: 20
    title: Position
    value: Position
  demographics:
  - full name
  - nickname
  - gender
  - hair
  - eyes
  - skin
  - height
  - physique
  - played by
  - birthdate
  disable_auto_shortcuts: false
  editable_properties:
  - full name
  - nickname
  - gender
  - hair
  - physique
  genders:
    Male:
      possessive_pronoun: his
      subjective_pronoun: he
      objective_pronoun: him
      noun: man
    Female:
      possessive_pronoun: her
      subjective_pronoun: she
      objective_pronoun: her
      noun: woman
    Other:
      possessive_pronoun: their
      subjective_pronoun: they
      objective_pronoun: them
      noun: person
  groups:
    Allegiance:
      desc: |-
        Which faction with which do you have **public** allegiance?
        For instance, you can be a Cylon in the Colonial fleet.  In this case you would choose Colonial, choose the Colony they are allegedly from if they have implanted memories or have adopted a planet as their own.
      wiki: ''
      values:
        Colonial: Your public allegiance is to the colonies.
        Cylon: Your public allegaince is to the cylons.  Currently not open for CG.
        Other: Do not set unless you have been instructed by staff.
    Faction:
      desc: Faction within the group with which you have public allegiance
      wiki: ''
      values:
        Navy: Air and space flight, combat, aka all operation.
        Marines: Ground forces and key ship boarding defense.
    Department:
      desc: Typically military based departments.  NCOs are typically allowed and
        appointed to departments that only have enlisted.  Ask Staff when in doubt!
      wiki: ''
      values:
        Air Wing: Viper and Raptor crews. [Officers Only]
        Deck: Take care of the fighter ships, hangars, and other various things. [Enlisted]
        Marines: Boots on the ground (snipers and SF are restricted). [Officers Typically
          In Leadership Positions and Enlisted]
        Medical: All medical personnel, parajumpers (PJs are restricted), and corpsman
          [Officers and Enlisted]
        Engineering: Both those who work on general ship systems outside of Deck's
          domain (save for aeronautical craft design). [Officers Only]
        Sciences: The study of the sciences or locating various signs of life, sources
          of water, etc. [Typically Officers]
        Command: This includes all CIC support.  If you work in CIC a la TACCO, Intel,
          communications officer, etc. [Officers Only]
        Other: Do not set unless you have been instructed by staff.
    Colony:
      desc: Your character's home world, what they think their homeworld is (Cylons),
        or what homeworld they have pledged personal allegiance to (Cylons).
      wiki: ''
      values:
        Aerilon: Bread basket of the colonies.
        Aquaria: Cold, harsh world popular with tourists.
        Canceron: Crowded and hot, a developing nation.
        Caprica: Rich center of colonial culture and industry.
        Gemenon: Fundamentalist religion and isolationist people.
        Leonis: Old imperialist empire in decline, still known for culture and fashion.
        Libran: Neutral colony renowned for fostering inter-colonial cooperation.
        Picon: Water world famous for its beaches and strong navy.
        Sagittaron: Poor colony,  oft-exploited, now carved into several protectorates.
        Scorpia: Lush jungles and bitter clan warfare. Home to shipyards used to construct
          Battlestars.
        Tauron: An up-and-coming socialist republic with a strong agricultural base
          and developing industries.
        Virgon: A monarchy in decline, clinging to old traditions.
    Position:
      desc: Job.  Positions with an asterisk (*) in the description represent restricted
        roles and require staff approval.
      wiki: ''
      values:
        Viper Pilot: Navy - Viper pilot
        Raptor Pilot: Navy - Raptor pilot
        Raptor ECO: Navy - Raptor Electronic Countermeasures Officer
        Rifleman: Marine - Average rank and file
        Gunner: Marine - Support/heavy weapons specialist.  We also include artillery,
          but usually this is a specialty in and of itself and should be acquired
          thus via action skill specialties.
        Combat Engineer: Marine - **Minor** field demolitons, construction, maintenance.
        Marksman: Marine - Designated Marksman* - encompasses all 'types' of DMs.  In
          comparison to snipers, their weapons aren't **as** long range, they don't
          receive specific sniper level training, but they help take down important
          targets in the battlefield.
        Sniper: Marine - Sniper* - What it sounds like.  Snipers work with spotters
          in pairs.
        Spotter: Marine - Spotter* - Spotters and snipers work in pairs.  The spotter
          assists in a number of duties not listed here.
        Recon: Marine - Reconaissance scout*
        EOD: Marine - Explosive Ordnance Disposal* - Does lots of things beyond just
          bombs and ieds.
        JTAC: Marine - Joint Terminal Attack Controller* - directs the action of combat
          aircraft engaged in close air support and other offensive air operations
          from a forward position.
        MP: Marine - Military Police - They are the police of the military.
        Corpsman: Navy - Battlefield medic that bunks and deploys with Marines
        Doctor: Navy - Medical doctor who may or may not specialize
        Surgeon: Navy - Medical doctor who specialized in some kind of surgery
        Psychiatrist: Navy - Medical doctor who provides psychiatric support (can
          write prescriptions, not a therapist)
        Psychologist: Navy - Psychologist or therapist who provides psychological
          support (cannot write prescriptions, focuses on diagnosis, therapy, and
          treatment coordination with a psychiatrist)
        Nurse: Navy - Nurse
        Parajumper: Navy - Parajumper* - Combat medical search and rescue, typically
          for downed personnel. Medical training, skilled parachutists, scuba divers
          and rock climbers, and trained for extreme environments
        Deck Crew: Navy - Air wing support/maintenance personnel.
        Prisoner: Starting - Prisoner till military.
        Other: Any other position.
  help_text:
    played by: "%xcplayedby <actor>%xn - Your 'dream casting' for your character."
    physique: "%xcphysique <build/body type>%xn - athletic, wiry, slim, pudgy, etc."
    gender: "%xcgender <male/female/other>%xn"
    hair: "%xchair <hair color>%xn"
    eyes: "%xceyes <eye color>%xn"
    skin: "%xcskin <complexion>%xn"
    birthdate: "%xcbirthdate <mm/dd/yyy>%xn or %xcage <years>%xn"
    nickname: |-
      %xcnickname<nickname>%xn - Those that have callsigns set this to callsign.  These are practical in military operations and critical for Pilots and ECOs. Unlike callsigns, Marines may have colloquial nicknames and they are not required for operation in the field.
      Currently these show up where player aliases are normally shown.  This is just a display bug for us to accommodate alias and nickname as separate concepts.
      We will handle this post launch, but for now, just let people know in a custom profile field with `profile/add alias=<alias>`
    colony: |-
      %xcnickname<colony>%xn - Your character's home world, what they think their homeworld is (Cylons), or what homeworld they have pledged personal allegiance to (Cylons).
      **Do not** change this after CG unless you have a reason staff would approve of such as a life event for your character.  This is a big deal.
    full name: "%xcfullname <name>%xn - Your character's full name."
  max_age: 65
  min_age: 18
  nickname_field: nickname
  nickname_format: "%{name} (%{nickname})"
  private_properties:
  - admin shared character note
  required_properties:
  - played by
  - hair
  - eyes
  - skin
  - height
  - physique
  - full name
  - gender
  - birthdate
  shortcuts:
    groups: group
    colonies: group colony
    demographics: demographic
    birthday: birthdate
    actors: census played by
    actor: demographic/set played by=
    fullname: demographic/set full name=
    playedby: demographic/set played by=
