---
describe:
  always_show_idle_in_rooms: false
  exit_end_bracket: "]"
  exit_start_bracket: "["
  glance_format: "%{height_title} height, %{age} year-old %{gender_noun} with %{hair}
    hair and %{eyes} eyes."
  shortcuts:
    l: look
    desc: describe
    of: outfit
    outfits: outfit
    outfits/c: outfit/set
    outfits/a: outfit/set
    outfits/r: outfit/delete
    outfits/rm: outfit/delete
    outfit/create: outfit/set
    outfit/add: outfit/set
    outfit/remove: outfit/delete
    det: detail
    detail/a: detail/set
    detail/c: detail/set
    detail/r: detail/delete
    detail/rm: detail/delete
    detail/add: detail/set
    detail/create: detail/set
    detail/remove: detail/delete
    view/add: detail/set
    view/create: detail/set
    view/remove: detail/delete
    view: look
    view/a: detail/set
    view/c: detail/set
    view/r: detail/delete
    view/rm: detail/delete
    vistas: vista
    vista/add: vista/set
    vista/create: vista/set
    vista/remove: vista/delete
    vista/a: vista/set
    vista/c: vista/set
    vista/r: vista/delete
    vista/rm: vista/delete
  tag_colors:
    admin: "%xg"
    beginner: "%xb"
    web: "%xh%xx"
