---
events:
  achievements:
    event_created:
      type: community
      message: Scheduled an event.
  event_alert_cron:
    minute:
    - 0
    - 15
    - 30
    - 60
  shortcuts:
    events: event
    event/add: event/create
    event/remove: event/delete
    event/a: event/create
    event/r: event/delete
    event/rm: event/delete
    evt: event
