game:
    name: "So Say We All"

    category: Sci-Fi
    
    description: "A private Battlestar Galactica themed MUSH"
    
    website: ""
        
    public_game: false
    
    status: In Development
