game:
    name: "Battlestar Rebooted"

    category: Sci-Fi
    
    description: "A private Battlestar Galactica themed MUSH."
    
    website: ""
        
    public_game: false
    
    status: In Development