---
login:
  activity_cron:
    minute:
    - 0
  allow_creation: false
  allow_web_registration: false
  blacklist_cron:
    day:
    - 1
    - 15
    hour:
    - 3
    minute:
    - 0
  creation_not_allowed_message: Humans and synthetic life by invite only.
  guest_disabled_message: No gawkers allowed.
  guest_role: guest
  login_not_allowed_message: The galaxy is taking a break.  After these messages,
    we\
  notice_cleanup_cron:
    day:
    - 18
    hour:
    - 2
    minute:
    - 19
  notice_timeout_days: 60
  portal_requires_registration: false
  shortcuts:
    logout: quit
    con: connect
    newpassword: password/reset
    conn: connect
    kick: boot
    password/change: password/set
    motd: notice/motd
