---
names:
  restricted:
  - me
  - here
  - Adama
  - Rosaline
  - Tigh
  - Cain
  - Apollo
  - Starbuck
  - Thrace
  - Boomer
  - Helo
  - Agathon
  - Tyrol
  - Gaeta
  - Anders
  - Zarek
  - Cottle
  - Seelix
  - Hotdog
  - Crashdown
  - Racetrack
  - Jammer
  - Kat
  - Jammer
  - One
  - Two
  - Three
  - Four
  - Five
  - Six
  - Seven
  - Eight
  - Nine
  - Ten
  - Eleven
  - Twelve
  - Thirteen
  - Fourteen
  - Fifteen
  - Sixteen
  - Seventeen
  - Eighteen
  - Nineteen
  - Twenty
