---
roles:
  admin_list_roles:
  - admin
  default_roles:
  - everyone
  restricted_roles:
  - admin
  - coder
  - storyteller
  - tester
  shortcuts:
    roles: role
    staff: admin
    role/add: role/assign
