server:
    hostname: 173.255.215.77

    port: 9000
    
    websocket_port: 4202

    web_portal_port: 80
    
    engine_api_port: 4203
    
    use_https: true
    
    certificate_file_path: '/home/ares/certs/fullchain.pem'
    
    private_key_file_path: '/home/ares/certs/privkey.pem'
