---
skin:
  divider: "%x!------------------------------------------------------------------------------%xn"
  footer: "%x!+==~~~~~====~~~~====~~~~====~~~~=====~~~~=====~~~~====~~~~====~~~~====~~~~~==+%xn"
  header: "%x!+==~~~~~====~~~~====~~~~====~~~~=====~~~~=====~~~~====~~~~====~~~~====~~~~~==+%xn"
  line_with_text:
    default:
      color: "%x!"
      pattern: _-_
      text_position: 5
      left_bracket: "[ "
      right_bracket: " ]"
  plain: "%x!+==~~~~~====~~~~====~~~~====~~~~=====~~~~=====~~~~====~~~~====~~~~====~~~~~==+%xn"
  random_colors:
  - "%xc"
  - "%xb"
  - "%xg"
  - "%xr"
