---
status:
  afk_cron:
    minute:
    - 20
  colors:
    IC: "%xb"
    OOC: "%xh"
    NPC: "%xh"
    AFK: "%xy"
    NEW: "%xr"
    ADM: "%xg"
    WEB: "%xh"
  minutes_before_idle: 25
  minutes_before_idle_disconnect: 300
  shortcuts:
    ic: onstage
    afk on: afk
    afk/on: afk
    afk/off: afk off
