---
utils:
  shortcuts:
    colors: color
    think: echo
    "@@": keepalive
    "@": keepalive
    shortcut/remove: shortcut/delete
    note/remove: note/delete
    note/update: note/add
    die: dice
    notes: note
    i: echo %% There's some lint in your pocket.
    in: echo %% There's some lint in your pocket.
    inv: echo %% There's some lint in your pocket.
