---
website:
  achievements:
    wiki_create:
      type: portal
      message: Created a wiki page.
    wiki_edit:
      type: portal
      message: Edited a wiki page.
  allow_html_in_markdown: true
  character_gallery_group: Faction
  character_gallery_subgroup: Department
  left_sidebar: false
  max_folder_size_kb: 2000
  max_upload_size_kb: 600
  restricted_pages:
  - home
  - theme:*
  - policy:*
  - plot:*
  - cg:*
  - template:*
  - include:*
  sitemap_update_cron:
    hour:
    - 2
    minute:
    - 17
  top_navbar:
  - title: Join
    menu:
    - title: Create a Character
      route: chargen
    - title: Pre-Made Characters
      route: roster
    - title: CG Walkthrough
      route: wiki-page
      id: cg:cg-walkthrough
    - title: Policies
      route: wiki-page
      id: policy:policies
    - title: FAQ
      route: wiki-page
      id: policy:faq
  - title: Play
    menu:
    - title: Active Scenes
      route: scenes-live
    - title: My Scenes
      route: scenes-play
    - title: Start New Scene
      route: scene-create
    - divider: true
    - title: Who's Online
      route: who
    - title: Chat
      route: chat
    - title: Forum
      route: forum
    - title: Mail
      route: mail
    - divider: true
    - title: Play via Web Client
      route: play
    - divider: true
    - title: RP Aids
      route: wiki-page
      id: theme:rp-aids
  - title: Colonial Theme
    menu:
    - title: Colonials
      route: wiki-page
      id: theme:colonials
    - title: Colonial Plot
      route: wiki-page
      id: plot:colonial-plot
    - title: Timeline
      route: wiki-page
      id: plot:timeline
    - divider: true
    - title: Colonial Planets
      route: wiki-page
      id: theme:colonial-planets
    - title: Colonial History
      route: wiki-page
      id: theme:colonial-history
    - title: Colonial Military
      route: wiki-page
      id: theme:colonial-military
    - title: Colonial Government
      route: wiki-page
      id: theme:colonial-goverment
    - title: Colonial Culture
      route: wiki-page
      id: theme:colonial-culture
    - title: Colonial Religion
      route: wiki-page
      id: theme:colonial-religion
    - title: Colonial Technology
      route: wiki-page
      id: theme:colonial-technology
  - title: Cylon Theme
    menu:
    - title: Cylons
      route: wiki-page
      id: theme:cylons
    - title: Cylon Plot
      route: wiki-page
      id: plot:cylon-plot
    - title: Timeline
      route: wiki-page
      id: plot:timeline
    - divider: true
    - title: Cylon Planets
      route: wiki-page
      id: theme:cylon-planets
    - title: Cylon History
      route: wiki-page
      id: theme:cylon-history
    - title: Colonial Military
      route: wiki-page
      id: theme:colonial-military
    - title: Cylon Government
      route: wiki-page
      id: theme:cylon-goverment
    - title: Cylon Culture
      route: wiki-page
      id: theme:cylon-culture
    - title: Cylon Religion
      route: wiki-page
      id: theme:cylon-religion
    - title: Cylon Technology
      route: wiki-page
      id: theme:cylon-technology
  - title: Directory
    menu:
    - title: Characters
      route: characters
    - title: Scenes
      route: scenes
    - title: Plots
      route: plots
    - divider: true
    - title: Players
      route: players
    - title: Census
      route: census
    - title: Roster
      route: roster
    - title: Locations
      route: locations
    - title: Combats
      route: combats
    - divider: true
    - title: Files
      route: files
  - title: System
    menu:
    - title: Abilities List
      route: fs3skills-abilities
    - title: Gear List
      route: fs3combat-gear
    - title: Groups List
      route: groups
    - title: Skill Limits
      route: fs3-limits
    - title: XP Costs
      route: fs3-xp-costs
    - title: Achievements
      route: achievements
    - divider: true
    - target: blank
      title: FS3 Player's Guide <i class="fa fa-external-link-alt" aria-hidden="true">
      url: http://aresmush.com/fs3/fs3-3
    - target: blank
      title: FS3 Combat Quick Reference <i class="fa fa-external-link-alt" aria-hidden="true">
      url: http://aresmush.com/fs3/fs3-3/combat-quickref.html
    - target: blank
      title: FS3 Interactive Combat Walkthrough <i class="fa fa-external-link-alt"
        aria-hidden="true">
      url: http://aresmush.com/fs3/fs3-3/combat-walkthrough.html
  - title: Wiki
    menu:
    - title: Home
      route: wiki
    - divider: true
    - title: Create New Page
      route: wiki-create
    - title: All Pages
      route: wiki-all
    - title: Search Wiki
      route: search-wiki
    - title: Tags
      route: wiki-tags
    - title: Recent Changes
      route: recent-changes
    - divider: true
    - title: Files
      route: files
    - id: markdown
      title: Editing Help
      route: help-topic
  - title: Help
    menu:
    - title: Search
      route: search-wiki
    - divider: true
    - title: Requests
      route: jobs
    - title: Account
      route: account
    - title: Game Admin
      route: admins
    - divider: true
    - title: Game Help
      route: help
    - id: markdown
      title: Markdown Reference
      route: help-topic
    - title: Terms of Service
      route: tos
    - divider: true
    - target: blank
      title: MUSH 101 Tutorial <i class="fa fa-external-link-alt" aria-hidden="true">
      url: https://aresmush.com/mush-101/
  website_code_path: "/home/ares/ares-webportal"
  wiki_aliases:
    main: home
